[encrypt_info]
key = [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
]

iv = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

[client_config]
key_log = true
host = "567890"
port = 8080
cert = "567890"
rebind = true

[server_config]
key_log = true
ky = "567890"
cert = "567890"
stateless_retry = true
listen = "0.0.0.0"

[peer_storage]
path = "/Users/redeone/Git/rose/data/"